pub const Error = error{
    EOF,
    MagicHeaderNotDetected,
    UnknownBinaryVersion,
    MalformedFunctypeMagicNumber,
    MalformedSectionId,
    MalformedElemKind,
    MalformedImportKind,
    MalformedExportKind,
    MalformedValueType,
    MalformedLimitId,
    MalformedRefType,
    MalformedMutId,
    MalformedBlockType,
    TypeMismatch,
    OtherError,
};
